# Generated by Django 3.1.7 on 2021-02-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depto',
            name='puesto',
        ),
    ]
