# Generated by Django 3.1.7 on 2021-02-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('dni', models.CharField(max_length=9)),
                ('telefono', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='TutorA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('dni', models.CharField(max_length=9)),
                ('telefono', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('dni', models.CharField(max_length=9)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
                ('tutor_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a', to='alumnos.tutora')),
                ('tutor_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b', to='alumnos.tutorb')),
            ],
        ),
    ]
