# Generated by Django 3.1.7 on 2021-02-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
        ('alumnos', '0002_auto_20210228_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono3', to='contactos.contactos'),
        ),
        migrations.AlterField(
            model_name='tutora',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono1', to='contactos.contactos'),
        ),
        migrations.AlterField(
            model_name='tutorb',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono2', to='contactos.contactos'),
        ),
    ]
