# Generated by Django 3.1.7 on 2021-02-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('alumnos', '0003_auto_20210228_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tutora',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tutora',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='tutora',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='tutora',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tutorb',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tutorb',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='tutorb',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='tutorb',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers3', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='tutora',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers1', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='tutorb',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers2', to='personas.persona'),
        ),
    ]
