# Generated by Django 3.1.7 on 2021-03-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto'),
        ('alumnos', '0004_auto_20210228_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono3', to='contactos.contacto'),
        ),
        migrations.AlterField(
            model_name='tutora',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono1', to='contactos.contacto'),
        ),
        migrations.AlterField(
            model_name='tutorb',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono2', to='contactos.contacto'),
        ),
    ]
