# Generated by Django 3.1.7 on 2021-02-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depto', '0002_remove_depto_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depto.depto')),
            ],
        ),
    ]
